apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - name:  kube-scheduler-plugin
    image: elan01/custom-plugin:latest
    ports:
    - containerPort: 8888
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=0.0.0.0
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    - --config=/etc/kubernetes/manifests/scheduler/config.yaml
    image: registry.k8s.io/kube-scheduler:v1.25.3
    name: kube-scheduler
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/kubernetes/manifests/scheduler/config.yaml
      name: scheduler-config
      readOnly: true
  hostNetwork: true
  restartPolicy: Always
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: File
    name: kubeconfig
  - hostPath:
      path: /etc/kubernetes/manifests/scheduler/config.yaml
      type: File
    name: scheduler-config    