apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      schedulerName: custom-scheduler
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1